[package]
name = "SiteSavior"
version = "0.1.0"
authors = ["Anass Zakar"]
edition = "2018"

[dependencies]
rocket = "0.5.0-rc.3"
config = "0.13.3"
lazy_static = "1.4.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
sha256 = "1.1.2"
sys-info = "0.9.1"